[window]
opacity = 0.7
padding = { x = 15, y = 15 }
dynamic_padding = true

[font]
size=10.0

[font.normal]
family = "DroidSansM Nerd Font"
style = "regular"

[colors.primary]
background = "#05080f"
foreground = "#cce6ff"

[colors.normal]
black	= "#05080f"
red	= "#ff0055"
green	= "#39ff14"
#yellow	= "#ffcc00"
yellow  = "#ffea00"
blue	= "#0a4cf6"
#magenta = "#f000ff"
magenta = "#d94dff"
cyan	= "#00f0ff"
white	= "#f0f8ff"

[colors.bright]
black	= "#1d2638"
red	= "#ff3377"
green	= "#33ffb8"
yellow	= "#ffff33"
blue	= "#5c9bff"
magenta = "#f533ff"
cyan	= "#33f3ff"
white	= "#ffffff"
