# =======================================
# ANIMATIONS & FADING
# =======================================

fading = true;
fade-delta = 4;
fade-in-step = 0.03;
fade-out-step = 0.03;

# ======================================
# CORNERS
# ======================================

corner-radius = 6;
rounded-corners-exlude = [
	"window-type = 'dock'",
	"class_g = 'rofi'"
];

# ======================================
# SHADOWS
# ======================================

shadow = false;
shadow-radius = 0;
shadow-opacity = 0;
shadow-offset-x = -15;
shadow-offset-y = -15;
shadow-exlude = [
	"window-type = 'dock'",
        "class_g = 'rofi'"
];

# ======================================
# BLUR & TRANSPARENCY
# ======================================

active-opacity = 1;
inactive-opacity = 1;

# on VM couldnt blue
blur-method = "dual_kawase"
blur-strength = 1;
blur-background = true;

# ======================================
# BACKEND (CRITICAL FOR PERFORMANCE)
# ======================================

# using xrandr because setup was done in VM
backend = "glx";
vsync = true;
use-damage = true;
glx-no-stencil = true;
